num_list=[]
print("num_list:",num_list)
print("datatype:",type(num_list))
num_list2=list()
print("num_list2:",num_list2)
num_list3=[1,2,3,4,5]
print("num_list3:",num_list3)
num_list4=list(range(1,11))
print("num_list4:",num_list4)
even_num=list(range(0,21,2))
print("even_num:",even_num)
odd_num=list(range(1,21,2))
print("odd_num:",odd_num)
